ens_job_index:
    path:     /
    defaults: { _controller: "EnsTotoBundle:Job:index" }
    methods:  GET

ens_job_show:
    path:     /{company}/{location}/{id}/{position}
    defaults: { _controller: "EnsTotoBundle:Job:show" }
    requirements:
        id:  \d+
    methods:  GET

ens_job_preview:
    path:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "EnsTotoBundle:Job:preview" }
    requirements:
        token:  \w+

ens_job_publish:
    path:  /{token}/publish
    defaults: { _controller: "EnsTotoBundle:Job:publish" }
    methods: POST

ens_job_new:
    path:     /new
    defaults: { _controller: "EnsTotoBundle:Job:new" }
    methods:  [GET, POST]

ens_job_edit:
    path:     /{token}/edit
    defaults: { _controller: "EnsTotoBundle:Job:edit" }
    methods:  [GET, POST]

ens_job_delete:
    path:     /{token}/delete
    defaults: { _controller: "EnsTotoBundle:Job:delete" }
    methods:  POST

ens_job_extend:
    path:  /{token}/extend
    defaults: { _controller: "EnsTotoBundle:Job:extend" }
    methods: POST