ens_toto_ens_job:
    resource: "@EnsTotoBundle/Resources/config/routing/job.yml"
    prefix:   /ens_job

ens_toto_homepage:
    path:     /
    defaults: { _controller: EnsTotoBundle:Default:index }
