EnsTotoBundle_job:
    resource: "@EnsTotoBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsTotoBundle_category:
    path:  /category/{slug}/{page}
    defaults: { _controller: EnsTotoBundle:Category:show,  page: 1 }

EnsTotoBundle_homepage:
    path:  /
    defaults: { _controller: EnsTotoBundle:Job:index }

login:
    pattern:   /login
    defaults:  { _controller: EnsTotoBundle:Security:login }
login_check:
    pattern:   /login_check

logout:
    path:   /logout