EnsTotoBundle_job:
    resource: "@EnsTotoBundle/Resources/config/routing/job.yml"
    prefix: /job

ens_toto_homepage:
    path:     /hello/{name}
    defaults: { _controller: EnsTotoBundle:Default:index }
