EnsTotoBundle_job:
    resource: "@EnsTotoBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsTotoBundle_category:
    pattern:  /category/{slug}
    defaults: { _controller: EnsTotoBundle:Category:show }

EnsTotoBundle_homepage:
    pattern:  /
    defaults: { _controller: EnsTotoBundle:Job:index }